
<Mein>
    GridLayout:
        cols: 1
        row_force_default: True
        row_default_height: 40

        Label:
            text: '▼表示テキストの入力▼'
            size_hint_x: None
            width: 160

        BoxLayout:
            # size_hint: 0.5, 0.05
            pos: 10, 400
            line_height: 1
            multiline: False
            # pos_hint: {'center_x': .5, 'center_y': .2}
            TextInput:
                size_hint: 10, 0.1
                id: input_text
            Button:
                size_hint: 2, 0.1
                text: '実行'
                # on_release: root.widgets_list_add(

        # CheckBox:
        #     pos_hint: {'center_x': .1, 'center_y': .5}
        #     active: True

        # Button:
        #     text: 'setting'
        #     font_size: 10
        #     pos: 500, 3


        # CustomSpinner:
        #     text: 'リスト'
        #     values: '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'
        #     size_hint: None, None
        #     size: 100, 44
        #     pos_hint: {'center_x': .5, 'center_y': .5}
        #     on_text: root.on_spinner_change(self.text)

        # TextInput:
        #     size_hint: 0.5, 0.05
        #     pos: 200, 50
        #     line_height: 1
        #     multiline: False